#/bin/bash

LIPSUM=$(cat <<'EOF'
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla tempor, purus et ornare convallis, turpis sapien dictum tortor, nec fringilla arcu eros in dui. Aenean in ullamcorper quam. Phasellus a ultrices eros. Nulla fringilla lorem orci, non ullamcorper mauris eleifend vel. Nam vitae est eu sapien mollis fringilla. Suspendisse varius lectus sit amet commodo semper. In hac habitasse platea dictumst.

Nam consectetur posuere sapien non placerat. Sed fermentum, tellus at ultrices vehicula, tellus neque tristique leo, a finibus nunc enim at ex. Etiam dictum, lectus vitae ultrices varius, felis diam ultricies libero, bibendum pretium orci turpis nec magna. In scelerisque libero eros, volutpat sodales odio imperdiet id. Sed suscipit massa at volutpat lacinia. Praesent volutpat commodo consectetur. Nam fermentum mattis augue, dictum lacinia justo ultrices ut. Sed ac imperdiet est, sed gravida ex. Nunc iaculis nibh efficitur orci dapibus sagittis. Etiam dignissim ipsum ex, et tristique massa elementum pretium. Vestibulum lacus ipsum, finibus non ipsum volutpat, posuere dignissim libero. Aliquam ut nibh semper, viverra erat nec, facilisis ipsum. Nullam id pellentesque purus. Lorem ipsum dolor sit amet, consectetur adipiscing elit.

Cras nibh lorem, pretium a velit et, vestibulum tincidunt sem. In volutpat sodales hendrerit. Nulla scelerisque sagittis mi ac cursus. Donec aliquet ex congue, tincidunt erat at, ultricies justo. Mauris congue ornare lacus in facilisis. Mauris vitae scelerisque sem. Sed cursus justo nec lectus venenatis, at imperdiet dui iaculis. Vivamus porttitor lacus at velit semper imperdiet. Aliquam vel augue elit.

Donec placerat vitae nisi quis tempor. Suspendisse potenti. Donec mollis quam vel molestie sollicitudin. Nullam ultrices lorem nibh, sit amet fringilla sapien viverra nec. Morbi porttitor placerat tristique. Proin feugiat turpis nulla, ultrices commodo lectus tincidunt nec. Cras vestibulum tempor sem quis aliquet. Quisque at euismod lacus, in malesuada lectus. Nullam neque justo, maximus sit amet convallis eget, iaculis id elit.

Nullam ut ipsum auctor, tempus felis quis, fringilla ante. Duis sodales gravida erat, vel ullamcorper leo pretium eget. Quisque sollicitudin aliquet felis non pretium. Ut ullamcorper sed eros sed eleifend. Aenean a nibh a neque sollicitudin feugiat vel ut urna. Quisque vel odio non sapien mollis posuere eget et turpis. Vestibulum rutrum lacinia pharetra. Sed rhoncus lorem a tellus facilisis interdum. Proin non sollicitudin ligula. Curabitur fringilla scelerisque velit in finibus.

Cras purus dui, iaculis eget nunc id, volutpat elementum quam. Maecenas libero nulla, volutpat et hendrerit at, vestibulum sed dolor. Nullam vel urna non metus euismod blandit et eget felis. Vestibulum rhoncus odio in ex viverra, ac placerat turpis elementum. In quis ex eros. Nullam et ante diam. In sit amet ligula id dolor tincidunt auctor. Donec quis sollicitudin leo. Nulla vel purus consectetur, interdum dui vel, placerat ipsum. Nulla volutpat ante eu vehicula congue. Praesent in massa a lorem tristique ullamcorper. Integer pellentesque est sed lacus porttitor, quis sodales dolor aliquam. Pellentesque dignissim mollis libero quis fermentum.

Mauris malesuada finibus feugiat. Vivamus vestibulum tortor in dui fermentum scelerisque. Morbi nulla quam, consectetur pharetra vulputate ac, cursus at purus. Fusce sed molestie ex. Cras nibh neque, rutrum eget ante eget, consectetur pharetra tortor. Duis mattis leo ut tortor pharetra condimentum. Nam gravida, massa id iaculis tempor, leo nunc blandit odio, vitae suscipit quam turpis eu mi. Mauris dui dolor, lacinia non nunc sit amet, tempus venenatis mi.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum in ipsum ultricies, vestibulum magna a, egestas purus. Donec eu suscipit augue. Donec aliquam sapien leo, quis interdum metus semper lacinia. Etiam eu odio vel justo bibendum laoreet. Nunc ut sollicitudin magna. Aliquam vehicula nisl et euismod laoreet. Suspendisse pretium lobortis dui non porta. Cras in arcu vel massa euismod posuere quis ultrices tortor. Pellentesque interdum mauris metus, ac suscipit velit semper non. Phasellus porttitor purus ut pellentesque dignissim. Aliquam nec elit at mi bibendum fringilla at vitae leo. Fusce quis accumsan eros. Duis porttitor, magna eu tincidunt tincidunt, sapien nunc porta odio, ornare hendrerit sem nisl nec urna.

Maecenas viverra nibh sit amet arcu congue bibendum. Phasellus faucibus orci eget dolor iaculis congue. Pellentesque id sapien vestibulum ligula posuere aliquet quis lacinia nulla. Maecenas ultrices ex ornare leo cursus, nec cursus purus vestibulum. Etiam lectus nibh, tempus ut quam semper, laoreet dictum mauris. Vestibulum vel consectetur libero. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur at urna gravida, scelerisque risus at, cursus libero. Quisque felis erat, accumsan a condimentum a, consectetur ut mi.

Nam a ex efficitur, consequat nibh eu, malesuada nisi. Curabitur porta dolor purus, fringilla eleifend magna volutpat vitae. Nullam metus diam, blandit at ornare id, tincidunt at urna. Vivamus dictum lobortis placerat. Fusce volutpat ante sed metus consectetur bibendum. Donec sagittis, tellus ut rutrum commodo, mauris felis blandit tellus, sed egestas massa magna eget justo. Phasellus at volutpat ligula, in laoreet quam. Vestibulum convallis massa erat, a accumsan massa pretium non. Vestibulum ornare condimentum nisl, eget tristique nisl. Donec viverra risus ut est tristique, ut condimentum augue venenatis. Cras ultricies mauris eu sollicitudin accumsan. Nunc id aliquam libero, vitae fringilla diam. Morbi eget quam ac nisi facilisis placerat.

Morbi urna magna, tempus non tincidunt at, maximus eget ligula. Maecenas rhoncus vehicula lectus sit amet accumsan. Sed tincidunt id nibh ut eleifend. Mauris vitae massa eros. Curabitur quis faucibus est. Aliquam vel maximus arcu. Sed accumsan ac augue aliquet vestibulum. Curabitur vitae nunc sit amet augue aliquet malesuada. Sed aliquet facilisis porta. Donec semper ac sem id facilisis. Cras tincidunt consectetur mauris a imperdiet. Phasellus laoreet lacus nulla, at porta ipsum lobortis ac.

Quisque vitae blandit leo, eu congue leo. Suspendisse eget risus non dui aliquet imperdiet eget et diam. Aenean condimentum, mi egestas sagittis ultrices, risus tellus tincidunt erat, at scelerisque nulla tellus et risus. Morbi elementum laoreet felis euismod imperdiet. Vivamus suscipit et metus tristique vestibulum. Donec volutpat neque viverra urna efficitur, non faucibus mauris egestas. In non nunc nec mauris iaculis faucibus ultricies sit amet nibh.

Integer eleifend sem enim, id lacinia ipsum dignissim eu. Sed dignissim rutrum condimentum. Nam maximus sapien sed est pulvinar gravida. Ut vel turpis ut neque imperdiet tempus. Donec consectetur quam sollicitudin pulvinar ultricies. Proin blandit tincidunt mauris, quis euismod urna feugiat sed. Vestibulum efficitur, erat sed dapibus ultrices, nisi tortor volutpat augue, eu ullamcorper nisi dolor non augue. Ut cursus aliquet tincidunt. Ut mauris nunc, sagittis ut suscipit a, dictum ac tellus. Ut eget eros non nulla scelerisque euismod. Morbi ex magna, pellentesque non ante sit amet, iaculis tristique augue. In ac molestie elit. Curabitur pulvinar ex vitae nulla lacinia eleifend. Sed bibendum ultrices dolor, in dapibus felis vestibulum in. Pellentesque sollicitudin sem non tellus feugiat dignissim. Morbi interdum pulvinar augue, in porta nisi ultrices quis.

Sed venenatis, libero nec placerat tempus, velit odio porta justo, vitae semper metus urna a lorem. Maecenas blandit, massa sed volutpat pellentesque, felis enim molestie nunc, sed sodales tellus quam sit amet dolor. Integer id consequat tortor, laoreet dapibus urna. Quisque finibus urna in feugiat porttitor. In porta mi sed ex mollis, et posuere dolor efficitur. Maecenas quis semper quam. Curabitur enim quam, mattis eu tortor a, auctor tristique massa. Proin nisi metus, vulputate eu molestie vel, dictum sit amet tellus. Phasellus nisl ex, pretium ac condimentum sit amet, tempor id orci. Pellentesque scelerisque commodo magna, non auctor enim tincidunt id.

Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum in dignissim leo. Maecenas ac eros hendrerit, maximus lorem vel, pulvinar turpis. Cras scelerisque eros volutpat felis volutpat lacinia. Aenean posuere dui et tincidunt semper. Etiam imperdiet varius pharetra. Integer aliquam, elit quis mollis aliquet, eros lacus ultrices mauris, vitae porttitor est eros ut nulla. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Duis consequat gravida tortor non varius. In ac tempor odio, ac pretium metus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum et ipsum vitae magna egestas dapibus. Morbi quis venenatis elit. Aenean venenatis, ex a faucibus pretium, libero ipsum viverra elit, vel porttitor eros risus bibendum elit. Fusce efficitur massa nunc, id dictum arcu pharetra eu. Curabitur mollis orci elit, ultrices lobortis ex hendrerit quis.

Quisque vel sem eget diam auctor scelerisque id quis justo. Proin velit velit, vehicula quis tristique eu, mattis sit amet tellus. Nullam eget purus nec massa mollis pulvinar. Suspendisse id tortor commodo, ultrices lacus a, facilisis est. Nullam pretium ligula vitae eleifend tincidunt. Vestibulum non metus aliquet, egestas neque non, facilisis ligula. Aenean mattis tellus a dictum laoreet. Fusce sollicitudin id metus sed accumsan. Ut fermentum elit lacinia dui dapibus eleifend. Duis dapibus nibh sed placerat consectetur. Pellentesque sapien enim, laoreet et aliquam eget, dapibus at sem. Vestibulum dignissim vehicula turpis vitae pellentesque. In euismod posuere leo, eu facilisis velit pellentesque vel. Cras porttitor laoreet enim, sed iaculis nulla tincidunt nec.

Aliquam ut pretium diam. Ut rutrum id libero sed mattis. Quisque mollis enim in turpis blandit, varius viverra sapien porta. Nunc non tristique lacus. In porta scelerisque rutrum. Morbi vehicula iaculis sagittis. Pellentesque venenatis bibendum feugiat. Ut interdum viverra elit, in scelerisque lorem posuere gravida.

Quisque hendrerit, ante sed dapibus faucibus, lectus nisl egestas libero, vitae egestas neque lectus ac nibh. Pellentesque varius facilisis viverra. Quisque nibh lectus, rhoncus ut auctor sit amet, rhoncus sed arcu. Phasellus semper et lacus ac luctus. Vivamus cursus vulputate turpis facilisis imperdiet. Suspendisse dapibus urna eget tempus tristique. Aenean a orci mollis ex bibendum aliquam. Nam eget rutrum nibh, id dignissim nisl. Proin mollis massa eu velit bibendum, nec finibus justo pellentesque. Ut accumsan varius arcu, eu accumsan turpis porta euismod. Etiam aliquam leo magna, dictum viverra eros ultrices non. Mauris sit amet lacinia turpis. Donec imperdiet ipsum ac quam feugiat, eu porttitor libero rhoncus. In non gravida mauris.

Vivamus vestibulum sit amet dui vitae feugiat. Proin euismod mollis tortor, at scelerisque nulla eleifend vel. Maecenas eu ligula id turpis faucibus dignissim. Proin sollicitudin vulputate magna vel consectetur. Cras aliquam mattis nibh et elementum. Quisque condimentum lobortis porttitor. Morbi ullamcorper mi in risus feugiat semper. Etiam et massa molestie, sollicitudin mauris in, aliquam est. Quisque sollicitudin rutrum purus non maximus. Morbi vitae augue id erat elementum laoreet sed sed turpis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Suspendisse elementum mollis accumsan. Quisque eu turpis facilisis, dictum metus a, consectetur leo. Fusce in imperdiet turpis, at finibus erat. Lorem ipsum dolor sit amet, consectetur adipiscing elit.

Donec vel libero vitae ante posuere tincidunt sit amet id neque. Sed sem nisi, hendrerit nec rhoncus quis, gravida in metus. Vestibulum eu fermentum neque, sed sagittis purus. Nullam eros risus, rhoncus consectetur volutpat vitae, semper at justo. Nunc eget libero at ipsum dignissim aliquam. Ut at elit metus. Suspendisse fermentum felis ipsum, nec elementum ante varius vel. Donec imperdiet efficitur nisi, id mollis mauris efficitur id. Donec et neque vehicula, commodo velit pellentesque, fermentum arcu. Aenean faucibus vehicula arcu non pulvinar. Etiam placerat sit amet lacus ut interdum. Cras euismod faucibus nunc sed faucibus. Pellentesque eget elit purus. Aenean mollis bibendum tellus, facilisis tincidunt quam facilisis finibus. 
EOF
)

TEMPLATE="capitulo-%02d.txt"
INDEX=1

rm -f $(printf "$TEMPLATE" $INDEX)

while read line; do
    echo "$line" >> $(printf "$TEMPLATE" $INDEX)
    if [ "$line" = "" ]; then
        # Si viene un párrafo nuevo lo pasamos a otro archivo
        let INDEX++
        rm -f $(printf "$TEMPLATE" $INDEX)
    fi
done <<< "$LIPSUM"

